In [1]:
import numpy as np


In [2]:
x = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([0,0,0,1])

In [6]:

x.shape,y.shape

((4, 2), (4, 1))

In [7]:
y = np.array([[0,0,0,1]]).T
y.shape

(4, 1)

In [ ]:
def sig(z):
    return (1/1+np.exp(-z))


In [1]:
def dersig(z):
    return sig(z)*(1-sig(z))


In [14]:
#NO hidden layer weights
weights = 2 * np.random.random((2, 1)) -1
bias = 2  * np.random.random(1) -1
weights, bias

(array([[-0.68548948],
        [-0.58216482]]),
 array([0.4637351]))

In [15]:
#Forward propagation without any hidden layer
out0 = x
out = sig(np.dot(out0, weights)+bias)
out

array([[1.62893013],
       [2.12572775],
       [2.24826473],
       [3.23428036]])

In [27]:
#With hidden layer weights
wh = 2 * np.random.random((2, 2)) -1
bh = 2  * np.random.random((1,2)) -1
wo = 2 * np.random.random((2, 1)) -1
bo = 2  * np.random.random((1,1)) -1

In [28]:
out0 = x
outh = sig(np.dot(out0, wh)+bh)
out = sig(np.dot(outh, wo)+bo)
out

array([[1.14332438],
       [1.33412175],
       [1.01597169],
       [1.0949667 ]])