# Numpy

In [6]:
import numpy as np

l1 = [2,1,3,4]
a1 = np.array(l1)

In [7]:
l1

[2, 1, 3, 4]

In [8]:
a1

array([2, 1, 3, 4])

In [13]:
type(l1)

numpy.ndarray

In [12]:
type(a1)

numpy.ndarray

In [14]:
l1 + 1

TypeError: can only concatenate list (not "int") to list

In [15]:
a1+1 #vector operation

array([3, 2, 4, 5])

In [43]:
#2d list
l2 = [[2,5,4,3],[4,3,4,5]]
a2 = np.array(l2)

In [44]:
l2

[[2, 5, 4, 3], [4, 3, 4, 5]]

In [45]:
a2

array([[2, 5, 4, 3],
       [4, 3, 4, 5]])

In [46]:
type(l2)

list

In [21]:
type(a2)

numpy.ndarray

In [47]:
a2+1

array([[3, 6, 5, 4],
       [5, 4, 5, 6]])

In [24]:
l2+1

TypeError: can only concatenate list (not "int") to list

In [26]:
a3 = np.array(l2,dtype=float)
a3

array([[2., 3.],
       [4., 5.]])

In [28]:
a4 = a3.astype(int)
a4

array([[2, 3],
       [4, 5]])

In [29]:
a5 = np.array(l2,dtype=bool)
a5

array([[ True,  True],
       [ True,  True]])

In [30]:
a6 = np.array([2,0,2.0,'y',True], dtype = 'object')
a6

array([2, 0, 2.0, 'y', True], dtype=object)

In [31]:
l4 = a6.tolist()
l4

[2, 0, 2.0, 'y', True]

# array dimension

In [49]:
a2

array([[2, 5, 4, 3],
       [4, 3, 4, 5]])

In [50]:
a2.shape


(2, 4)

In [51]:
a2.size

8

In [53]:
a2.dtype

dtype('int32')

In [54]:
a2.ndim


2

In [ ]:
#reversing rows n cols

In [55]:
a2

array([[2, 5, 4, 3],
       [4, 3, 4, 5]])

In [57]:
a2[::-1]#reverse row

array([[4, 3, 4, 5],
       [2, 5, 4, 3]])

In [60]:
a2[::-1 , ::-1] # reverse rows n cols

array([[5, 4, 3, 4],
       [3, 4, 5, 2]])

# specific element extraction

In [61]:
a2

array([[2, 5, 4, 3],
       [4, 3, 4, 5]])

In [66]:
a2[0,:]


array([2, 5, 4, 3])

In [67]:
a2[:1,:]

array([[2, 5, 4, 3]])

In [68]:
a2[:2,:]

array([[2, 5, 4, 3],
       [4, 3, 4, 5]])

In [69]:
a2[:2,:2]

array([[2, 5],
       [4, 3]])

In [70]:
a2[:-1,:]

array([[2, 5, 4, 3]])

In [71]:
a2[:,:-1]

array([[2, 5, 4],
       [4, 3, 4]])

# statistics


In [73]:
a2

array([[2, 5, 4, 3],
       [4, 3, 4, 5]])

In [75]:
a2.min()

2

In [76]:
a2.max()

5

In [81]:
a2.mean() #or
np.average(a2)

3.75

In [78]:
a2.sum()

30

In [79]:
a2.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [80]:
np.median(a2)

4.0

In [82]:
np.var(a2)

0.9375

# reshape or flatten

In [83]:
a2

array([[2, 5, 4, 3],
       [4, 3, 4, 5]])

In [85]:
a2.shape

(2, 4)

In [86]:
a2.reshape(1,8)

array([[2, 5, 4, 3, 4, 3, 4, 5]])

In [87]:
a2.reshape(1,7)

ValueError: cannot reshape array of size 8 into shape (1,7)

In [88]:
a2.reshape(4,2)

array([[2, 5],
       [4, 3],
       [4, 3],
       [4, 5]])

In [89]:
a2.reshape(8,1)

array([[2],
       [5],
       [4],
       [3],
       [4],
       [3],
       [4],
       [5]])

In [90]:
a2

array([[2, 5, 4, 3],
       [4, 3, 4, 5]])

In [94]:
f = a2.flatten()
f

array([2, 5, 4, 3, 4, 3, 4, 5])

In [93]:
a2.ndim

2

In [95]:
f.ndim

1

# random arrays and sequences

In [97]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
np.arange(2,10)#start stop step

array([2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [100]:
np.arange(10,0) #wont print in descending

array([], dtype=int32)

In [101]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [102]:
np.linspace(1,10,3)#start stop total elem

array([ 1. ,  5.5, 10. ])

In [103]:
np.linspace(1,10,6)#start stop total elem

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [105]:
 np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [106]:
 np.zeros([3,3,3])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

# unique items and count

In [108]:
arr = [[1,4,5,2,2,3],
      [4,4,4,4,5,5]]

In [109]:
arr

[[1, 4, 5, 2, 2, 3], [4, 4, 4, 4, 5, 5]]

In [110]:
np.unique(arr)

array([1, 2, 3, 4, 5])

In [115]:
u,c = np.unique(arr, return_counts = True)
c

array([1, 2, 1, 5, 3], dtype=int64)

In [114]:
u

array([1, 2, 3, 4, 5])