# Numpy Tutorial

In [2]:
import numpy as np

In [4]:
l = [1,2,3,4]
a = np.array(l)
a


array([1, 2, 3, 4])

In [5]:
a = np.zeros(l)
a


array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [6]:
a = np.ones(l)
a


array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])