## Importing libraries

In [2]:
#faster than list
#compact than list
#can be used to store homogenous data faster
import numpy as np

In [3]:
l = [1,2,3]
np.array(l)


array([1, 2, 3])

In [4]:
l = [1,2,'a']
np.array(l)


array(['1', '2', 'a'], dtype='<U11')

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
a = np.ones(10)
a.dtype

dtype('float64')

In [10]:
a = np.ones(10, int)
a.dtype

dtype('int32')

In [16]:
a = np.ones((2,3,2))
a

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [17]:
a = np.ones((2,3,))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
print(a[2:4])

[]


In [20]:
a.shape

(2, 3)

In [24]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a[0:2, 2]

array([3, 6])

### Operations

In [26]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b) # shud be same dimension
print(a+2) # elem wise operatoin -,*, / ...

[5 7 9]
[3 4 5]


In [33]:
print(a.mean())


print(a.sum())

2.0
6


#### sqrt((x1-x2)^2 + (y1-y2)^2)

In [36]:
#distance between 2 points
import math as m
a = np.array([1,2,3])
b = np.array([5,6,7])
d = ((a-b)**2).sum()
m.sqrt(d)

6.928203230275509

#### E(xi-x.mean)^2

In [37]:
x = np.array([1,3,5,6])
((x-x.mean())**2).sum()

14.75

In [38]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[10,20],[30,40]])
a1.dot(a2)



array([[ 70, 100],
       [150, 220]])