## Importing libraries

In [160]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder

import matplotlib.pyplot as plt

### Loading datasets

In [161]:
data = pd.read_csv("iris.csv", sep = ',')
data.head()

sepal-length  sepal-width  petal-length  petal-width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

### Data preprocessing

### Label Encoding

In [162]:
l_enc = LabelEncoder()


In [163]:
s_len = l_enc.fit_transform(data['sepal-length'])
s_wid = l_enc.fit_transform(data['sepal-width'])
p_len = l_enc.fit_transform(data['petal-length'])
p_wid = l_enc.fit_transform(data['petal-width'])
cls = l_enc.fit_transform(data['class'])
for i in range(len(cls)):
    print(data['class'][i],cls[i])

Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-versicolor 1
Iris-versicolor 1
Iris-versicolor 1
Iris-versicolor 1
Iris-versicolor 1
Iris-versicolor 1
Iris-versicolor 1
Iris-versicolor 1
Iris-versicolor 1
Iris-versicolor 1
Iris-versicolor 1
Iris-versicolor 1
Iris-versicolor 1
Iris-versicolor 1
Iris-versicolor 1
Iris-versicolor 1
Iris-versico

### Zip all the details to one list

In [187]:
x = list(zip(s_len,s_wid,p_len,p_wid))
y = list(cls)

### Training data

In [165]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)

In [166]:
d = {
    0 :'Iris-setosa',
    1 : 'Iris-versicolor',
    2 :'Iris-virginica'
}

# Linear Regression

In [167]:
from sklearn.linear_model import LinearRegression

In [168]:
linear = LinearRegression()
linear.fit(x_train,y_train)

LinearRegression()

In [169]:
linear.coef_

array([-0.01194609, -0.02246938,  0.03273342,  0.07472249])

In [170]:
linear.intercept_

0.14497361057610503

##### Accuracy

In [171]:
acc = linear.score(x_test,y_test)
acc

0.9230462172216696

In [188]:
predict = linear.predict(x_test)
predict

array([ 1.23385989,  2.05457187,  1.82939601,  1.14086873, -0.03872287,
        0.12283116,  0.87522289, -0.24826162,  0.10929931,  2.13109713,
        1.68152898,  1.07535966,  0.91974725,  2.17939215,  1.45645723,
        0.15346032, -0.26458019, -0.01946243,  1.91321118,  2.01593907,
        1.18828391, -0.04562282, -0.00557505,  1.28595785,  0.06762836,
        0.31679267,  1.25028256,  1.32069143,  2.18674874,  1.19507977,
        0.00763868,  1.83560569,  0.83576911,  2.2418052 ,  2.38399469,
        1.26695666,  0.12114912,  0.79208137,  0.91553773,  1.45451593,
        1.01642061,  0.30779628,  1.24996445,  1.60591883,  1.99230615])

In [172]:

for i in range(len(predict)):
    z = predict[i].round()
    a = ""
    if(d[z] == d[y_test[i]]):
        a = "same"
    else:
        a = "diff"
    print(d[z],x_test[i],d[y_test[i]],a)
    


Iris-versicolor (17, 13, 21, 12) Iris-versicolor same
Iris-virginica (21, 7, 32, 17) Iris-virginica same
Iris-virginica (21, 6, 29, 15) Iris-virginica same
Iris-versicolor (9, 6, 15, 10) Iris-versicolor same
Iris-setosa (9, 14, 5, 1) Iris-setosa same
Iris-setosa (3, 10, 5, 1) Iris-setosa same
Iris-versicolor (13, 8, 12, 9) Iris-versicolor same
Iris-setosa (9, 20, 5, 0) Iris-setosa same
Iris-setosa (11, 13, 5, 3) Iris-setosa same
Iris-virginica (33, 7, 41, 16) Iris-virginica same
Iris-virginica (16, 9, 27, 14) Iris-virginica same
Iris-versicolor (27, 11, 23, 10) Iris-versicolor same
Iris-versicolor (15, 6, 15, 8) Iris-versicolor same
Iris-virginica (33, 9, 37, 19) Iris-virginica same
Iris-versicolor (20, 4, 25, 11) Iris-versicolor same
Iris-setosa (8, 17, 8, 3) Iris-setosa same
Iris-setosa (12, 21, 4, 1) Iris-setosa same
Iris-setosa (8, 17, 5, 2) Iris-setosa same
Iris-virginica (26, 10, 27, 19) Iris-virginica same
Iris-virginica (21, 11, 29, 19) Iris-virginica same
Iris-versicolor (20, 

# SVM

In [173]:
from sklearn import svm
from sklearn import metrics

In [174]:

svm0 = svm.SVC()
svm0.fit(x_train, y_train)


SVC()

##### Prediction

In [175]:
svm_pred = svm0.predict(x_test)
svm_pred

array([1, 2, 2, 1, 0, 0, 1, 0, 0, 2, 2, 1, 1, 2, 1, 0, 0, 0, 2, 2, 1, 0,
       0, 1, 0, 0, 1, 1, 2, 1, 0, 2, 1, 2, 2, 1, 0, 1, 1, 2, 1, 0, 1, 2,
       2])

##### Accuracy

In [176]:
svm_acc = metrics.accuracy_score(y_test,svm_pred)
svm_acc

1.0

In [177]:
for i in range(len(svm_pred)):
    z = svm_pred[i]
    a = ""
    if(d[z] == d[y_test[i]]):
        a = "same"
    else:
        a = "diff"
    print(d[z],x_test[i],d[y_test[i]],a)
    

Iris-versicolor (17, 13, 21, 12) Iris-versicolor same
Iris-virginica (21, 7, 32, 17) Iris-virginica same
Iris-virginica (21, 6, 29, 15) Iris-virginica same
Iris-versicolor (9, 6, 15, 10) Iris-versicolor same
Iris-setosa (9, 14, 5, 1) Iris-setosa same
Iris-setosa (3, 10, 5, 1) Iris-setosa same
Iris-versicolor (13, 8, 12, 9) Iris-versicolor same
Iris-setosa (9, 20, 5, 0) Iris-setosa same
Iris-setosa (11, 13, 5, 3) Iris-setosa same
Iris-virginica (33, 7, 41, 16) Iris-virginica same
Iris-virginica (16, 9, 27, 14) Iris-virginica same
Iris-versicolor (27, 11, 23, 10) Iris-versicolor same
Iris-versicolor (15, 6, 15, 8) Iris-versicolor same
Iris-virginica (33, 9, 37, 19) Iris-virginica same
Iris-versicolor (20, 4, 25, 11) Iris-versicolor same
Iris-setosa (8, 17, 8, 3) Iris-setosa same
Iris-setosa (12, 21, 4, 1) Iris-setosa same
Iris-setosa (8, 17, 5, 2) Iris-setosa same
Iris-virginica (26, 10, 27, 19) Iris-virginica same
Iris-virginica (21, 11, 29, 19) Iris-virginica same
Iris-versicolor (20, 

##### Adding kernel

In [178]:
svm1 = svm.SVC(kernel = "linear")
svm1.fit(x_train, y_train)
svm_pred1 = svm1.predict(x_test)

In [179]:
svm_acc1 = metrics.accuracy_score(y_test,svm_pred1)
svm_acc1

0.9555555555555556

In [180]:
for i in range(len(svm_pred1)):
    z = svm_pred1[i]
    a = ""
    if(d[z] == d[y_test[i]]):
        a = "same"
    else:
        a = "diff"
    print(d[z],x_test[i],d[y_test[i]],a)
    

Iris-versicolor (17, 13, 21, 12) Iris-versicolor same
Iris-virginica (21, 7, 32, 17) Iris-virginica same
Iris-virginica (21, 6, 29, 15) Iris-virginica same
Iris-versicolor (9, 6, 15, 10) Iris-versicolor same
Iris-setosa (9, 14, 5, 1) Iris-setosa same
Iris-setosa (3, 10, 5, 1) Iris-setosa same
Iris-versicolor (13, 8, 12, 9) Iris-versicolor same
Iris-setosa (9, 20, 5, 0) Iris-setosa same
Iris-setosa (11, 13, 5, 3) Iris-setosa same
Iris-virginica (33, 7, 41, 16) Iris-virginica same
Iris-virginica (16, 9, 27, 14) Iris-virginica same
Iris-versicolor (27, 11, 23, 10) Iris-versicolor same
Iris-versicolor (15, 6, 15, 8) Iris-versicolor same
Iris-virginica (33, 9, 37, 19) Iris-virginica same
Iris-versicolor (20, 4, 25, 11) Iris-versicolor same
Iris-setosa (8, 17, 8, 3) Iris-setosa same
Iris-setosa (12, 21, 4, 1) Iris-setosa same
Iris-setosa (8, 17, 5, 2) Iris-setosa same
Iris-virginica (26, 10, 27, 19) Iris-virginica same
Iris-virginica (21, 11, 29, 19) Iris-virginica same
Iris-versicolor (20, 

# KNN algorithm

In [181]:
from sklearn.neighbors import KNeighborsClassifier


In [182]:
knn = KNeighborsClassifier(n_neighbors=11)
knn

KNeighborsClassifier(n_neighbors=11)

#### Fitting and prediction

In [183]:
knn.fit(x_train,y_train)
knn_pred = knn.predict(x_test)
knn_pred

array([1, 2, 2, 1, 0, 0, 1, 0, 0, 2, 2, 1, 1, 2, 1, 0, 0, 0, 2, 2, 1, 0,
       0, 1, 0, 0, 1, 1, 2, 1, 0, 2, 1, 2, 2, 1, 0, 1, 1, 2, 1, 0, 1, 2,
       2])

##### Accuracy

In [185]:
knn_acc = metrics.accuracy_score(y_test,knn_pred)
knn_acc

1.0

In [191]:
for i in range(len(knn_pred)):
    a = ""
    if(d[knn_pred[i]] == d[y_test[i]]):
        a = "same"
    else:
        a = "diff"
    print(d[knn_pred[i]],x_test[i],d[y_test[i]],a)
    

Iris-versicolor (17, 13, 21, 12) Iris-versicolor same
Iris-virginica (21, 7, 32, 17) Iris-virginica same
Iris-virginica (21, 6, 29, 15) Iris-virginica same
Iris-versicolor (9, 6, 15, 10) Iris-versicolor same
Iris-setosa (9, 14, 5, 1) Iris-setosa same
Iris-setosa (3, 10, 5, 1) Iris-setosa same
Iris-versicolor (13, 8, 12, 9) Iris-versicolor same
Iris-setosa (9, 20, 5, 0) Iris-setosa same
Iris-setosa (11, 13, 5, 3) Iris-setosa same
Iris-virginica (33, 7, 41, 16) Iris-virginica same
Iris-virginica (16, 9, 27, 14) Iris-virginica same
Iris-versicolor (27, 11, 23, 10) Iris-versicolor same
Iris-versicolor (15, 6, 15, 8) Iris-versicolor same
Iris-virginica (33, 9, 37, 19) Iris-virginica same
Iris-versicolor (20, 4, 25, 11) Iris-versicolor same
Iris-setosa (8, 17, 8, 3) Iris-setosa same
Iris-setosa (12, 21, 4, 1) Iris-setosa same
Iris-setosa (8, 17, 5, 2) Iris-setosa same
Iris-virginica (26, 10, 27, 19) Iris-virginica same
Iris-virginica (21, 11, 29, 19) Iris-virginica same
Iris-versicolor (20, 

# K means CLustering

In [192]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import scale

In [202]:
kmeans = KMeans(n_clusters=3, init="random", n_init=10)
kmeans.fit(x_train,y_train)

KMeans(init='random', n_clusters=3)

In [203]:
kmeans_pred = kmeans.predict(x_test)
kmeans_pred

array([2, 0, 0, 2, 1, 1, 2, 1, 1, 0, 2, 2, 2, 0, 2, 1, 1, 1, 0, 0, 2, 1,
       1, 2, 1, 1, 2, 2, 2, 2, 1, 2, 2, 0, 0, 2, 1, 1, 2, 2, 2, 1, 0, 0,
       0])

In [205]:
km_acc = metrics.accuracy_score(y_test,kmeans_pred)
km_acc

0.1111111111111111

In [206]:
for i in range(len(kmeans_pred)):
    a = ""
    if(d[kmeans_pred[i]] == d[y_test[i]]):
        a = "same"
    else:
        a = "diff"
    print(d[kmeans_pred[i]],x_test[i],d[y_test[i]],a)
    

Iris-virginica (17, 13, 21, 12) Iris-versicolor diff
Iris-setosa (21, 7, 32, 17) Iris-virginica diff
Iris-setosa (21, 6, 29, 15) Iris-virginica diff
Iris-virginica (9, 6, 15, 10) Iris-versicolor diff
Iris-versicolor (9, 14, 5, 1) Iris-setosa diff
Iris-versicolor (3, 10, 5, 1) Iris-setosa diff
Iris-virginica (13, 8, 12, 9) Iris-versicolor diff
Iris-versicolor (9, 20, 5, 0) Iris-setosa diff
Iris-versicolor (11, 13, 5, 3) Iris-setosa diff
Iris-setosa (33, 7, 41, 16) Iris-virginica diff
Iris-virginica (16, 9, 27, 14) Iris-virginica same
Iris-virginica (27, 11, 23, 10) Iris-versicolor diff
Iris-virginica (15, 6, 15, 8) Iris-versicolor diff
Iris-setosa (33, 9, 37, 19) Iris-virginica diff
Iris-virginica (20, 4, 25, 11) Iris-versicolor diff
Iris-versicolor (8, 17, 8, 3) Iris-setosa diff
Iris-versicolor (12, 21, 4, 1) Iris-setosa diff
Iris-versicolor (8, 17, 5, 2) Iris-setosa diff
Iris-setosa (26, 10, 27, 19) Iris-virginica diff
Iris-setosa (21, 11, 29, 19) Iris-virginica diff
Iris-virginica (2