## Importing libraries

In [317]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder

import matplotlib.pyplot as plt

### Loading datasets

In [318]:
data = pd.read_csv("iris.csv", sep = ',')
data.head()

sepal-length  sepal-width  petal-length  petal-width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

#### details of the data

In [319]:
data.shape

(150, 5)

In [320]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal-length  150 non-null    float64
 1   sepal-width   150 non-null    float64
 2   petal-length  150 non-null    float64
 3   petal-width   150 non-null    float64
 4   class         150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [321]:
data.describe()

sepal-length  sepal-width  petal-length  petal-width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

### Label Encoding

In [322]:
l_enc = LabelEncoder()


In [323]:
s_len = l_enc.fit_transform(data['sepal-length'])
s_wid = l_enc.fit_transform(data['sepal-width'])
p_len = l_enc.fit_transform(data['petal-length'])
p_wid = l_enc.fit_transform(data['petal-width'])
cls = l_enc.fit_transform(data['class'])
for i in range(len(cls)):
    print(data['class'][i],cls[i])

Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-setosa 0
Iris-versicolor 1
Iris-versicolor 1
Iris-versicolor 1
Iris-versicolor 1
Iris-versicolor 1
Iris-versicolor 1
Iris-versicolor 1
Iris-versicolor 1
Iris-versicolor 1
Iris-versicolor 1
Iris-versicolor 1
Iris-versicolor 1
Iris-versicolor 1
Iris-versicolor 1
Iris-versicolor 1
Iris-versicolor 1
Iris-versico

### Zip all the details to one list

In [324]:
x = list(zip(s_len,s_wid,p_len,p_wid))
y = list(cls)

### Training data

In [325]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)

In [326]:
d = {
    0 :'Iris-setosa',
    1 : 'Iris-versicolor',
    2 :'Iris-virginica'
}

# Linear Regression

In [327]:
from sklearn.linear_model import LinearRegression

In [328]:
linear = LinearRegression()
linear.fit(x_train,y_train)

LinearRegression()

In [329]:
linear.coef_

array([-0.01213254, -0.02161165,  0.03460843,  0.06875811])

In [330]:
linear.intercept_

0.13000153493431787

##### Accuracy

In [331]:
acc = linear.score(x_test,y_test)
acc

0.930399136559098

In [332]:
predict = linear.predict(x_test)

In [333]:

for i in range(len(predict)):
    z = predict[i].round()
    a = ""
    if(d[z] == d[y_test[i]]):
        a = "same"
    else:
        a = "diff"
    print(d[z],x_test[i],d[y_test[i]],a)
    


Iris-versicolor (21, 11, 21, 11) Iris-versicolor same
Iris-versicolor (22, 7, 22, 11) Iris-versicolor same
Iris-setosa (0, 9, 1, 0) Iris-setosa same
Iris-versicolor (11, 9, 21, 11) Iris-versicolor same
Iris-virginica (24, 4, 34, 14) Iris-virginica same
Iris-setosa (5, 9, 4, 2) Iris-setosa same
Iris-setosa (11, 13, 5, 3) Iris-setosa same
Iris-versicolor (23, 9, 20, 10) Iris-versicolor same
Iris-versicolor (17, 1, 16, 6) Iris-versicolor same
Iris-virginica (26, 10, 27, 19) Iris-virginica same
Iris-virginica (22, 9, 34, 18) Iris-virginica same
Iris-virginica (24, 9, 28, 19) Iris-virginica same
Iris-virginica (17, 1, 26, 11) Iris-virginica same
Iris-versicolor (20, 7, 27, 11) Iris-virginica diff
Iris-setosa (7, 9, 6, 1) Iris-setosa same
Iris-setosa (6, 10, 5, 0) Iris-setosa same
Iris-setosa (1, 8, 4, 1) Iris-setosa same
Iris-virginica (18, 9, 25, 14) Iris-virginica same
Iris-versicolor (13, 9, 17, 9) Iris-versicolor same
Iris-setosa (11, 13, 7, 1) Iris-setosa same
Iris-setosa (4, 11, 3, 1)

# SVM

In [334]:
from sklearn import svm
from sklearn import metrics

In [335]:

svm0 = svm.SVC()
svm0.fit(x_train, y_train)


SVC()

##### Prediction

In [336]:
svm_pred = svm0.predict(x_test)
svm_pred

array([1, 1, 0, 1, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 0, 0, 0, 2, 1, 0, 0, 1,
       2, 0, 2, 2, 0, 1, 1, 2])

##### Accuracy

In [337]:
svm_acc = metrics.accuracy_score(y_test,svm_pred)
svm_acc

1.0

In [338]:
for i in range(len(svm_pred)):
    z = svm_pred[i]
    a = ""
    if(d[z] == d[y_test[i]]):
        a = "same"
    else:
        a = "diff"
    print(d[z],x_test[i],d[y_test[i]],a)
    

Iris-versicolor (21, 11, 21, 11) Iris-versicolor same
Iris-versicolor (22, 7, 22, 11) Iris-versicolor same
Iris-setosa (0, 9, 1, 0) Iris-setosa same
Iris-versicolor (11, 9, 21, 11) Iris-versicolor same
Iris-virginica (24, 4, 34, 14) Iris-virginica same
Iris-setosa (5, 9, 4, 2) Iris-setosa same
Iris-setosa (11, 13, 5, 3) Iris-setosa same
Iris-versicolor (23, 9, 20, 10) Iris-versicolor same
Iris-versicolor (17, 1, 16, 6) Iris-versicolor same
Iris-virginica (26, 10, 27, 19) Iris-virginica same
Iris-virginica (22, 9, 34, 18) Iris-virginica same
Iris-virginica (24, 9, 28, 19) Iris-virginica same
Iris-virginica (17, 1, 26, 11) Iris-virginica same
Iris-virginica (20, 7, 27, 11) Iris-virginica same
Iris-setosa (7, 9, 6, 1) Iris-setosa same
Iris-setosa (6, 10, 5, 0) Iris-setosa same
Iris-setosa (1, 8, 4, 1) Iris-setosa same
Iris-virginica (18, 9, 25, 14) Iris-virginica same
Iris-versicolor (13, 9, 17, 9) Iris-versicolor same
Iris-setosa (11, 13, 7, 1) Iris-setosa same
Iris-setosa (4, 11, 3, 1) 

##### Adding kernel

In [339]:
svm1 = svm.SVC(kernel = "linear")
svm1.fit(x_train, y_train)
svm_pred1 = svm1.predict(x_test)

In [340]:
svm_acc1 = metrics.accuracy_score(y_test,svm_pred1)
svm_acc1

0.9666666666666667

In [341]:
for i in range(len(svm_pred1)):
    z = svm_pred1[i]
    a = ""
    if(d[z] == d[y_test[i]]):
        a = "same"
    else:
        a = "diff"
    print(d[z],x_test[i],d[y_test[i]],a)
    

Iris-versicolor (21, 11, 21, 11) Iris-versicolor same
Iris-versicolor (22, 7, 22, 11) Iris-versicolor same
Iris-setosa (0, 9, 1, 0) Iris-setosa same
Iris-versicolor (11, 9, 21, 11) Iris-versicolor same
Iris-virginica (24, 4, 34, 14) Iris-virginica same
Iris-setosa (5, 9, 4, 2) Iris-setosa same
Iris-setosa (11, 13, 5, 3) Iris-setosa same
Iris-versicolor (23, 9, 20, 10) Iris-versicolor same
Iris-versicolor (17, 1, 16, 6) Iris-versicolor same
Iris-virginica (26, 10, 27, 19) Iris-virginica same
Iris-virginica (22, 9, 34, 18) Iris-virginica same
Iris-virginica (24, 9, 28, 19) Iris-virginica same
Iris-virginica (17, 1, 26, 11) Iris-virginica same
Iris-versicolor (20, 7, 27, 11) Iris-virginica diff
Iris-setosa (7, 9, 6, 1) Iris-setosa same
Iris-setosa (6, 10, 5, 0) Iris-setosa same
Iris-setosa (1, 8, 4, 1) Iris-setosa same
Iris-virginica (18, 9, 25, 14) Iris-virginica same
Iris-versicolor (13, 9, 17, 9) Iris-versicolor same
Iris-setosa (11, 13, 7, 1) Iris-setosa same
Iris-setosa (4, 11, 3, 1)

# KNN algorithm

In [342]:
from sklearn.neighbors import KNeighborsClassifier


In [343]:
knn = KNeighborsClassifier(n_neighbors=11)
knn

KNeighborsClassifier(n_neighbors=11)

#### Fitting and prediction

In [344]:
knn.fit(x_train,y_train)
knn_pred = knn.predict(x_test)
knn_pred

array([1, 1, 0, 1, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 0, 0, 0, 1, 1, 0, 0, 1,
       2, 0, 2, 2, 0, 1, 1, 2])

##### Accuracy

In [345]:
knn_acc = metrics.accuracy_score(y_test,knn_pred)
knn_acc

0.9666666666666667

In [346]:
for i in range(len(knn_pred)):
    a = ""
    if(d[knn_pred[i]] == d[y_test[i]]):
        a = "same"
    else:
        a = "diff"
    print(d[knn_pred[i]],x_test[i],d[y_test[i]],a)
    

Iris-versicolor (21, 11, 21, 11) Iris-versicolor same
Iris-versicolor (22, 7, 22, 11) Iris-versicolor same
Iris-setosa (0, 9, 1, 0) Iris-setosa same
Iris-versicolor (11, 9, 21, 11) Iris-versicolor same
Iris-virginica (24, 4, 34, 14) Iris-virginica same
Iris-setosa (5, 9, 4, 2) Iris-setosa same
Iris-setosa (11, 13, 5, 3) Iris-setosa same
Iris-versicolor (23, 9, 20, 10) Iris-versicolor same
Iris-versicolor (17, 1, 16, 6) Iris-versicolor same
Iris-virginica (26, 10, 27, 19) Iris-virginica same
Iris-virginica (22, 9, 34, 18) Iris-virginica same
Iris-virginica (24, 9, 28, 19) Iris-virginica same
Iris-virginica (17, 1, 26, 11) Iris-virginica same
Iris-virginica (20, 7, 27, 11) Iris-virginica same
Iris-setosa (7, 9, 6, 1) Iris-setosa same
Iris-setosa (6, 10, 5, 0) Iris-setosa same
Iris-setosa (1, 8, 4, 1) Iris-setosa same
Iris-versicolor (18, 9, 25, 14) Iris-virginica diff
Iris-versicolor (13, 9, 17, 9) Iris-versicolor same
Iris-setosa (11, 13, 7, 1) Iris-setosa same
Iris-setosa (4, 11, 3, 1)

# K means CLustering

In [347]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import scale

In [348]:
kmeans = KMeans(n_clusters=3, init="random", n_init=10)
kmeans.fit(x_train,y_train)

KMeans(init='random', n_clusters=3)

In [349]:
kmeans_pred = kmeans.predict(x_test)
kmeans_pred

array([0, 0, 2, 0, 1, 2, 2, 0, 0, 1, 1, 1, 0, 0, 2, 2, 2, 0, 0, 2, 2, 2,
       0, 2, 1, 1, 2, 0, 2, 1])

In [350]:
km_acc = metrics.accuracy_score(y_test,kmeans_pred)
km_acc

0.0

In [351]:
for i in range(len(kmeans_pred)):
    a = ""
    if(d[kmeans_pred[i]] == d[y_test[i]]):
        a = "same"
    else:
        a = "diff"
    print(d[kmeans_pred[i]],x_test[i],d[y_test[i]],a)
    

Iris-setosa (21, 11, 21, 11) Iris-versicolor diff
Iris-setosa (22, 7, 22, 11) Iris-versicolor diff
Iris-virginica (0, 9, 1, 0) Iris-setosa diff
Iris-setosa (11, 9, 21, 11) Iris-versicolor diff
Iris-versicolor (24, 4, 34, 14) Iris-virginica diff
Iris-virginica (5, 9, 4, 2) Iris-setosa diff
Iris-virginica (11, 13, 5, 3) Iris-setosa diff
Iris-setosa (23, 9, 20, 10) Iris-versicolor diff
Iris-setosa (17, 1, 16, 6) Iris-versicolor diff
Iris-versicolor (26, 10, 27, 19) Iris-virginica diff
Iris-versicolor (22, 9, 34, 18) Iris-virginica diff
Iris-versicolor (24, 9, 28, 19) Iris-virginica diff
Iris-setosa (17, 1, 26, 11) Iris-virginica diff
Iris-setosa (20, 7, 27, 11) Iris-virginica diff
Iris-virginica (7, 9, 6, 1) Iris-setosa diff
Iris-virginica (6, 10, 5, 0) Iris-setosa diff
Iris-virginica (1, 8, 4, 1) Iris-setosa diff
Iris-setosa (18, 9, 25, 14) Iris-virginica diff
Iris-setosa (13, 9, 17, 9) Iris-versicolor diff
Iris-virginica (11, 13, 7, 1) Iris-setosa diff
Iris-virginica (4, 11, 3, 1) Iris-

## Feature Scale

In [352]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss_x_train = ss.fit_transform(x_train)
ss_x_test = ss.fit_transform(x_test)


# Logistic regression

In [353]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(random_state = 0, solver='lbfgs', multi_class='auto')
lr.fit(ss_x_train,y_train)

LogisticRegression(random_state=0)

In [354]:
lr_y_pred = lr.predict(ss_x_test)
lr_y_pred

array([1, 1, 0, 1, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 0, 0, 0, 2, 1, 0, 0, 1,
       2, 0, 2, 2, 0, 1, 1, 2])

#### Accuracy

In [355]:
acc = lr.score(ss_x_test,y_test)
acc

1.0

In [356]:
for i in range(len(lr_y_pred)):
    a = ""
    if(d[lr_y_pred[i]] == d[y_test[i]]):
        a = "same"
    else:
        a = "diff"
    print(d[lr_y_pred[i]],x_test[i],d[y_test[i]],a)

Iris-versicolor (21, 11, 21, 11) Iris-versicolor same
Iris-versicolor (22, 7, 22, 11) Iris-versicolor same
Iris-setosa (0, 9, 1, 0) Iris-setosa same
Iris-versicolor (11, 9, 21, 11) Iris-versicolor same
Iris-virginica (24, 4, 34, 14) Iris-virginica same
Iris-setosa (5, 9, 4, 2) Iris-setosa same
Iris-setosa (11, 13, 5, 3) Iris-setosa same
Iris-versicolor (23, 9, 20, 10) Iris-versicolor same
Iris-versicolor (17, 1, 16, 6) Iris-versicolor same
Iris-virginica (26, 10, 27, 19) Iris-virginica same
Iris-virginica (22, 9, 34, 18) Iris-virginica same
Iris-virginica (24, 9, 28, 19) Iris-virginica same
Iris-virginica (17, 1, 26, 11) Iris-virginica same
Iris-virginica (20, 7, 27, 11) Iris-virginica same
Iris-setosa (7, 9, 6, 1) Iris-setosa same
Iris-setosa (6, 10, 5, 0) Iris-setosa same
Iris-setosa (1, 8, 4, 1) Iris-setosa same
Iris-virginica (18, 9, 25, 14) Iris-virginica same
Iris-versicolor (13, 9, 17, 9) Iris-versicolor same
Iris-setosa (11, 13, 7, 1) Iris-setosa same
Iris-setosa (4, 11, 3, 1) 

# Naive Bayes

In [357]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(ss_x_train,y_train)

GaussianNB()

#### Accuracy

In [360]:
acc = nb.score(ss_x_test,y_test)
acc

0.9666666666666667

In [359]:
nb_y_pred = nb.predict(ss_x_test)

In [361]:
z = nb_y_pred
for i in range(len(z)):
    a = ""
    if(d[z[i]] == d[y_test[i]]):
        a = "same"
    else:
        a = "diff"
    print(d[z[i]],x_test[i],d[y_test[i]],a)

Iris-versicolor (21, 11, 21, 11) Iris-versicolor same
Iris-versicolor (22, 7, 22, 11) Iris-versicolor same
Iris-setosa (0, 9, 1, 0) Iris-setosa same
Iris-versicolor (11, 9, 21, 11) Iris-versicolor same
Iris-virginica (24, 4, 34, 14) Iris-virginica same
Iris-setosa (5, 9, 4, 2) Iris-setosa same
Iris-setosa (11, 13, 5, 3) Iris-setosa same
Iris-versicolor (23, 9, 20, 10) Iris-versicolor same
Iris-versicolor (17, 1, 16, 6) Iris-versicolor same
Iris-virginica (26, 10, 27, 19) Iris-virginica same
Iris-virginica (22, 9, 34, 18) Iris-virginica same
Iris-virginica (24, 9, 28, 19) Iris-virginica same
Iris-versicolor (17, 1, 26, 11) Iris-virginica diff
Iris-virginica (20, 7, 27, 11) Iris-virginica same
Iris-setosa (7, 9, 6, 1) Iris-setosa same
Iris-setosa (6, 10, 5, 0) Iris-setosa same
Iris-setosa (1, 8, 4, 1) Iris-setosa same
Iris-virginica (18, 9, 25, 14) Iris-virginica same
Iris-versicolor (13, 9, 17, 9) Iris-versicolor same
Iris-setosa (11, 13, 7, 1) Iris-setosa same
Iris-setosa (4, 11, 3, 1)

# Decision Tree

In [365]:
from sklearn.tree import DecisionTreeClassifier  
dtc = DecisionTreeClassifier()
dtc.fit(ss_x_train,y_train)

DecisionTreeClassifier()

#### Accuracy

In [366]:
dtc_acc = dtc.score(ss_x_test,y_test)
dtc_acc

0.9

In [368]:
dtc_y_pred = dtc.predict(ss_x_test)

In [369]:
z = dtc_y_pred
for i in range(len(z)):
    a = ""
    if(d[z[i]] == d[y_test[i]]):
        a = "same"
    else:
        a = "diff"
    print(d[z[i]],x_test[i],d[y_test[i]],a)

Iris-versicolor (21, 11, 21, 11) Iris-versicolor same
Iris-versicolor (22, 7, 22, 11) Iris-versicolor same
Iris-setosa (0, 9, 1, 0) Iris-setosa same
Iris-versicolor (11, 9, 21, 11) Iris-versicolor same
Iris-virginica (24, 4, 34, 14) Iris-virginica same
Iris-setosa (5, 9, 4, 2) Iris-setosa same
Iris-setosa (11, 13, 5, 3) Iris-setosa same
Iris-versicolor (23, 9, 20, 10) Iris-versicolor same
Iris-versicolor (17, 1, 16, 6) Iris-versicolor same
Iris-virginica (26, 10, 27, 19) Iris-virginica same
Iris-virginica (22, 9, 34, 18) Iris-virginica same
Iris-virginica (24, 9, 28, 19) Iris-virginica same
Iris-versicolor (17, 1, 26, 11) Iris-virginica diff
Iris-versicolor (20, 7, 27, 11) Iris-virginica diff
Iris-setosa (7, 9, 6, 1) Iris-setosa same
Iris-setosa (6, 10, 5, 0) Iris-setosa same
Iris-setosa (1, 8, 4, 1) Iris-setosa same
Iris-virginica (18, 9, 25, 14) Iris-virginica same
Iris-versicolor (13, 9, 17, 9) Iris-versicolor same
Iris-setosa (11, 13, 7, 1) Iris-setosa same
Iris-setosa (4, 11, 3, 1

# Random Forest

In [371]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
rfc.fit(ss_x_train,y_train)

RandomForestClassifier()

#### Accuracy

In [373]:
rfc_acc = rfc.score(ss_x_test,y_test)
rfc_acc

0.9333333333333333

In [372]:
rfc_y_pred = rfc.predict(ss_x_test)

In [374]:
z = rfc_y_pred
for i in range(len(z)):
    a = ""
    if(d[z[i]] == d[y_test[i]]):
        a = "same"
    else:
        a = "diff"
    print(d[z[i]],x_test[i],d[y_test[i]],a)

Iris-versicolor (21, 11, 21, 11) Iris-versicolor same
Iris-versicolor (22, 7, 22, 11) Iris-versicolor same
Iris-setosa (0, 9, 1, 0) Iris-setosa same
Iris-versicolor (11, 9, 21, 11) Iris-versicolor same
Iris-virginica (24, 4, 34, 14) Iris-virginica same
Iris-setosa (5, 9, 4, 2) Iris-setosa same
Iris-setosa (11, 13, 5, 3) Iris-setosa same
Iris-versicolor (23, 9, 20, 10) Iris-versicolor same
Iris-versicolor (17, 1, 16, 6) Iris-versicolor same
Iris-virginica (26, 10, 27, 19) Iris-virginica same
Iris-virginica (22, 9, 34, 18) Iris-virginica same
Iris-virginica (24, 9, 28, 19) Iris-virginica same
Iris-versicolor (17, 1, 26, 11) Iris-virginica diff
Iris-versicolor (20, 7, 27, 11) Iris-virginica diff
Iris-setosa (7, 9, 6, 1) Iris-setosa same
Iris-setosa (6, 10, 5, 0) Iris-setosa same
Iris-setosa (1, 8, 4, 1) Iris-setosa same
Iris-virginica (18, 9, 25, 14) Iris-virginica same
Iris-versicolor (13, 9, 17, 9) Iris-versicolor same
Iris-setosa (11, 13, 7, 1) Iris-setosa same
Iris-setosa (4, 11, 3, 1

# XGboost

# Polynomial Regression

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
pr = PolynomialFeatures()
pr_x_train()
pr.fit(x_train,x_test)