# Bank Customer Churn

In [15]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler, LabelEncoder

from sklearn import metrics

In [16]:
le = LabelEncoder()
ss = StandardScaler()

In [17]:
data = pd.read_csv("Bank_Customer_Churn_dataset.csv")
print(data.head())

   RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         790

In [18]:
CustomerId = le.fit_transform(list(data["CustomerId"]))
Surname = le.fit_transform(list(data["Surname"]))
CreditScore = le.fit_transform(list(data["CreditScore"]))
Gender = le.fit_transform(list(data["Gender"]))
Tenure = le.fit_transform(list(data["Tenure"]))
IsActiveMember = le.fit_transform(list(data["IsActiveMember"]))
Exited = le.fit_transform(list(data["Exited"]))

In [19]:
x = list(zip(CustomerId,Surname,CreditScore,Gender,Tenure,IsActiveMember))
y = list(Exited)

In [36]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3)

In [37]:
ss_x_train = ss.fit_transform(x_train)
ss_x_test = ss.fit_transform(x_test)

In [22]:
d = {
    1:"Exited",
    0:"Not Exited"
}

# KNN Algorithm

In [23]:
from sklearn.neighbors import KNeighborsClassifier

In [24]:
knn = KNeighborsClassifier()
knn.fit(x_train, y_train)    
knn_y_pred = knn.predict(x_test)

In [25]:
acc = knn.score(x_test,y_test)
acc

0.765

In [26]:
acc = metrics.accuracy_score(y_test,knn_y_pred)
acc

0.765

In [27]:
for i in range(len(lr_y_pred)):
    a = ""
    if(d[lr_y_pred[i]] == d[y_test[i]]):
        a = "same"
    else:
        a = "diff"
    print(d[lr_y_pred[i]],x_test[i],d[y_test[i]],a)

NameError: name 'lr_y_pred' is not defined

# Logistic Regression

In [28]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LogisticRegression

In [29]:

lr = LogisticRegression()

In [38]:
lr.fit(ss_x_train,y_train)

LogisticRegression()

In [39]:
lr_y_test_pred = lr.predict(ss_x_test)
lr_y_train_pred = lr.predict(ss_x_train)
lr_y_train_pred,lr_y_test_pred

(array([0, 0, 0, ..., 0, 0, 0], dtype=int64),
 array([0, 0, 0, ..., 0, 0, 0], dtype=int64))

In [40]:
from sklearn.metrics import confusion_matrix
a = confusion_matrix(y_train,lr_y_train_pred)
b = confusion_matrix(y_test,lr_y_test_pred)
a,b

(array([[5563,    0],
        [1437,    0]], dtype=int64),
 array([[2400,    0],
        [ 600,    0]], dtype=int64))

In [41]:
from sklearn.metrics import classification_report
rep_test = classification_report(y_test,lr_y_test_pred)
rep_train = classification_report(y_train,lr_y_train_pred)
rep_train, rep_test

c:\users\hebbar\appdata\local\programs\python\python39\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\hebbar\appdata\local\programs\python\python39\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\hebbar\appdata\local\programs\python\python39\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average,

('              precision    recall  f1-score   support\n\n           0       0.79      1.00      0.89      5563\n           1       0.00      0.00      0.00      1437\n\n    accuracy                           0.79      7000\n   macro avg       0.40      0.50      0.44      7000\nweighted avg       0.63      0.79      0.70      7000\n',
 '              precision    recall  f1-score   support\n\n           0       0.80      1.00      0.89      2400\n           1       0.00      0.00      0.00       600\n\n    accuracy                           0.80      3000\n   macro avg       0.40      0.50      0.44      3000\nweighted avg       0.64      0.80      0.71      3000\n')

In [ ]:
acc = lr.score(ss_x_test,y_test)
acc

In [ ]:

for i in range(len(lr_y_test_pred)):
    a = ""
    if(d[lr_y_test_pred[i]] == d[y_test[i]]):
        a = "same"
    else:
        a = "diff"
    print(d[lr_y_test_pred[i]],x_test[i],d[y_test[i]],a)

# Naive Bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()

In [ ]:
nb.fit(ss_x_train,y_train)

In [ ]:
acc = nb.score(ss_x_test,y_test)
acc

In [ ]:
nb_y_pred = nb.predict(ss_x_test)
acc = metrics.accuracy_score(y_test,nb_y_pred)
acc

In [ ]:
z = nb_y_pred
for i in range(len(z)):
    a = ""
    if(d[z[i]] == d[y_test[i]]):
        a = "same"
    else:
        a = "diff"
    print(d[z[i]],x_test[i],d[y_test[i]],a)

# Decision Tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier  
dtc = DecisionTreeClassifier()
dtc.fit(ss_x_train,y_train)

In [ ]:
dtc_acc = dtc.score(x_test,y_test)
dtc_acc

In [ ]:
dtc_y_pred = dtc.predict(ss_x_test)
dtc_y_pred

In [ ]:
z = dtc_y_pred

for i in range(len(z)):
    a = ""
    if(d[z[i]] == d[y_test[i]]):
        a = 'same'
    else:
        a = "diff"
    print(d[z[i]],x_test[i],d[y_test[i]],a)